# Main config file for icon theme.
baseURL = "https://www.example.com/"
languageCode = "en-AU"
title = "PentaPod"

[params.hero]
  title = "PentaPod"
  description = "Providing the homeless community of the Bay Area with flexible, resilient, and easily transportable temporary housing. "

# Navigation section
[params.nav]
  mission = "Our Mission"
  team = "The Team"

[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "mission"
    title = "Mission"
    subtitle = ""
    description = "<p>PentaPod is a modular living system which aims to address the issue of homelessness in the Bay Area, CA. The PentaPod system, physically, is a pentagon shaped housing structure which allows for coverage all around in order to be resilient to weather and provides a transportable living arrangement. The building itself is comprised of pentagon-shaped hard plastic, which can be arranged to make the interior?s area bigger or smaller depending on the needs of users. Because of this, the PentaPod provides a way to create homes that are suitable for everyone due to its flexibility. Currently, the PentaPod system is being developed to solve the housing issues that have arisen in the Bay Area. Though we will stay true to what works in our own community, there is also room to generalize and help out thousands of people. Alongside this expansion, we are also interested in displaced people, social protesters, and siding with those in need of one basic human right: the right to shelter. This long term goal calls for expanding the focus to refugees and social protesters (i.e. DAPL protests).</p>"

  [[params.mission.item]]
    weight = 2
    name = "why"
    title = "Why"
    subtitle = ""
    description = "<p>Currently, there are approximately 7,500 homeless residents in San Francisco. This population is extremely vulnerable, and largely made up of children, youth, women, racial minorities, people with mental illnesses and LGBTQ individuals. All are subject to extremely harsh conditions such as: physical and sexual violence, hunger, disease, and a lack of adequate health care. PentaPod would help provide shelter and safety for those that have been overlooked for years. A stable home is the first step towards a job and a better life. Pentapod is a mobile home designed by high school students to address the problem of poverty and homelessness head on. Its unique design of  allows it to be easily folded, packed, and expanded to include more pod space for families. Not only does Pentapod offer shelter, it provides visibility with colorful art work, removing the stigma of homelessness. The first step for our project would be to become established as a nonprofit unit and begin distributing throughout San Francisco with the help of grants such as this one and the help of the City of San Francisco.</p>"

[params.team]
  enable = true
  title = "Meet The Team"
  description = ""

  [[params.team.item]]
    name = "Anna Kondylis"
    position = "God Emperor"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/anna.jpg"

  [[params.team.item]]
    name = "Audrey Kost"
    position = "Lord Ruler"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/audrey.jpg"

  [[params.team.item]]
    name = "Natalie Avida"
    position = "Seargent Jumpfish"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/natalie.jpg"

  [[params.team.item]]
    name = "Nikhil Patel"
    position = "Seargent Jumpfish"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/nikhil.jpg"

  [[params.team.item]]
    name = "Noah Howard"
    position = "Seargent Jumpfish"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/noah.jpg"

  [[params.team.item]]
    name = "Sanam Yusuf"
    position = "Seargent Jumpfish"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/sanam.jpg"

  [[params.team.item]]
    name = "Sanjana Vissapragada"
    position = "Seargent Jumpfish"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/sanjana.jpg"

  [[params.team.item]]
    name = "Shiley Einav"
    position = "Seargent Jumpfish"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/shiley.jpg"

  # [[params.team.item]]
  #   name = "Blue Fish"
  #   position = "Cat Wrangler"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
